# Generated by Django 4.1.1 on 2022-09-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_first_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="currency",
            field=models.CharField(
                blank=True, choices=[("usd", "USD"), ("krw", "KRW")], max_length=3
            ),
        ),
    ]
